@startuml

'Diagramme de machine à états (PlantUML)'

'Configuration charte graphique'

'États et transitions'
state EnCréation : entry : constructeur()
state EnDestruction : entry : destructeur()

[*] -right-> EnCréation
EnCréation --> Accepté : post\n[u.getMembres().get(nomReseau).EstModerateur==True]\n/posterMessage(Utilisateur u)
EnCréation -right-> EnAttente : mise en attente\n[u.getMembres().get(nomReseau).EstModerateur==False]\n/posterMessage(Utilisateur u)
Accepté -right-> Caché : membre cache\n[hidden==True]\n/cacher(boolean hidden)
Caché -left-> Accepté : membre rend visible\n[hidden==False]\n/cacher(boolean hidden)
EnAttente --> Accepté : post\n[etat==ACCEPTE]\n/moderer(EtatMessage etat)
EnAttente --> EnDestruction : refus\n[etat==REFUSE]\n/moderer(EtatMessage etat)
EnAttente --> EnDestruction : supression du réseau
Accepté --> EnDestruction : supression du réseau
Caché --> EnDestruction : supression du réseau
EnDestruction -left-> [*]
@enduml
