@startuml

'Diagramme de séquence (PlantUML)'

'Configuration charte graphique'
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

'Déclaration des acteurs et des participants (déjà existants avant la séquence)'

actor "__adm:Administrateur__" as admin
participant "__m:MiniSocs__" as m

'Séquence avec les messages, les créations de participants, etc.'

admin -> m ++ : desactiverCompte(pseudo)
opt pseudo non null ∧ non vide
  m -> m ++ : u=chercherUtilisateur(pseudo): Utilisateur
  return
  m -> m ++ : e=checkEtatCompte(pseudo): EtatCompte
  return
  opt (u != null)^(e != BLOQUÉ)
    create "__u:Utilisateur__" as u
    m -> "__u:Utilisateur__" as u ++ : u=<<block(pseudo)>>
    return
  end
end
return
@enduml
