@startuml

'Diagramme de cas d'utilisation (PlantUML)'

'Configuration charte graphique'
skinparam usecase {
BackgroundColor White
BorderColor Black
ArrowColor Black
ActorBackgroundColor<< Human >> Gold
}

left to right direction

'Déclaration des acteurs :'
actor Administrateur
actor Moderateur
actor Membre
actor Utilisateur
Moderateur <|-- Administrateur
Membre <|-- Moderateur
Utilisateur <|-- Membre
'Déclaration des cas d'utilisation dans le système'
rectangle "MiniSocs" {

:Administrateur: -- (bloquer un compte utilisateur) 
:Administrateur: -- (ajouter un utilisateur) 
:Administrateur: -- (retirer un utilisateur) 
:Moderateur: -- (ajouter un membre) 
:Moderateur: -- (retirer un membre) 
:Moderateur: -- (promouvoir un membre) 
:Moderateur: -- (déstituer un modérateur)
:Moderateur: -- (lister les membres)
:Moderateur: -- (fermer son réseau social) 
:Moderateur: -- (modérer un message) 
:Moderateur:    <-- (notifier un message en attente de modération)
:Utilisateur:    -- (désactiver son compte) 
:Utilisateur:    -- (réactiver son compte) 
:Membre:    <-- (notifier un message accepté sur le réseau)
:Membre:    -- (poster un message)
:Membre:    -- (cacher son message) 
:Membre:    -- (définir son pseudo pour un réseau) 
:Membre:    -- (définir sa stratégie de notification) 
:Utilisateur:    -- (créer un réseau social) 
}

@enduml
