@startuml

'Diagramme de séquence (PlantUML)'

'Configuration charte graphique'
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

'Déclaration des acteurs et des participants (déjà existants avant la séquence)'

actor "__u:Utilisateur__" as u
participant "__m:MiniSocs__" as m 

'Séquence avec les messages, les créations de participants, etc.'

u -> m ++ : creerReseau(nomReseau, pseudoReseau)
opt u.pseudo, pseudoReseau, nomReseau non null ^ non vide
m -> m ++ : user=utilisateurs.get(u.pseudo)
return
opt (user != null)
m -> m ++ : ec=user.getEtatCompte()
return
m -> m ++ : r=reseaux.get(nomReseau)
return
opt (r == null) ∧ (ec == ACTIF)
create "__rs:RéseauSocial__" as rs
m -> rs ++ : new ReseauSocial(nomReseau)
return
create "__mem:Membre__" as mem
m -> mem ++ : new Membre(u,rs,pseudoReseau)
return
m -> u ++ : ajouterMembre(mem)
return
m -> rs ++ : ajouterMembre(mem)
return
m -> "__mem:Membre__" as mem ++ : setModerateur()
return



end
end
end
return
@enduml
