@startuml

'Diagramme de classes (PlantUML)'

'Configuration charte graphique'
hide empty methods
hide circle
skinparam class {
  BackgroundColor White
  ArrowColor Black
  BorderColor Black
}

'Classes, énumérations, etc.'

class MiniSocs {
  - nom: String
}
class Utilisateur {
  - pseudonyme: String
  - nom: String
  - prénom: String
  - courriel: String
  - etatCompte: ÉtatCompte
}

note left of Utilisateur: membres: Collection Membre

enum ÉtatCompte <<enum>> {
  ACTIF
  DESACTIVE
  BLOQUE
}
class Membre {
  - pseudoReseau: String
  - moderateur: boolean
}

note left of Membre: reseauSocial: ReseauSocial\nutilisateur: Utilisateur\nmessages: Collection Message


class ReseauSocial {
  - nom: String
  - etatReseau: EtatReseau
}

note right of ReseauSocial: membres: Collection Membre\nmessages: Collection Message

enum EtatReseau <<enum>> {
  FERMÉ
  OUVERT
}
class Message {
  - idMessage: int
  - contenu : String
  - etatMessage: EtatMessage
}
enum EtatMessage <<enum>> {
  ACCEPTE
  REFUSE
  ATTENTE
  CACHE
}

'Associations, etc.'
MiniSocs *--> "*" Utilisateur
MiniSocs *--> "*" Membre
MiniSocs *--> "*" Message
MiniSocs *--> "*" ReseauSocial
Utilisateur "1" -- "*" Membre
ReseauSocial "1" -- "*" Membre : < fait partie
Message "*"<-- "1" Membre : < a posté
ReseauSocial *--> "*" Message : > contient
'Au besoin, aides pour le positionnement'

@enduml
