@startuml

'Diagramme de cas d'utilisation (PlantUML)'

'Configuration charte graphique'
skinparam usecase {
BackgroundColor White
BorderColor Black
ArrowColor Black
ActorBackgroundColor<< Human >> Gold
}

left to right direction

'Déclaration des acteurs :'
actor Administrateur
actor Moderateur
actor Membre
Moderateur <|-- Administrateur
Membre <|-- Moderateur
'Déclaration des cas d'utilisation dans le système'
rectangle "MiniSocs" {

:Administrateur: -- (bloquer un compte utilisateur)
:Moderateur: -- (ajouter un utilisateur)
:Moderateur: -- (promouvoir un utilisateur)
:Moderateur: -- (lister les utilisateur)
:Moderateur: -- (fermer son réseau social)
:Moderateur: -- (accepter un message)
:Moderateur: -- (refuser un message)
:Membre:    -- (désactiver son compte)
:Membre:    -- (réactiver son compte)
:Membre:    -- (poster un message)
:Membre:    -- (cacher son message)
:Membre:    -- (initialiser son compte)
:Membre:    -- (définir son pseudo pour un réseau)
:Membre:    -- (créer un réseau social)
}

@enduml
